#!/bin/bash

function usage ()
{
        echo "Usage:"
        echo $0
        echo "-h   host"
        echo "-n   number of connects"
        exit 
}

if [ $# -eq 0 ]
then
        usage
fi

function connect ()
{
        retrycount=0

        while [[ $retrycount -lt $totalcount ]];do
                curl -L -s curl $proxyhost
                let count retrycount=$retrycount+1
        done
}

while getopts ":h:n:" opt; do
  case $opt in
    h)
        proxyhost=$OPTARG
        ;;
    n)
        totalcount=$OPTARG
        export totalcount 
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
    :)
        echo "Option -$OPTARG requires an argument." >&2
        exit 1
        ;;
  esac
done

connect|sort -n|uniq -c|awk '{print $2": "$1}'
